fit <- princomp(rawData[,unlist(innovation_blocks)], cor=TRUE)
summary(fit)
loadins(fit)
loadings(fit)
plot(fit, type="line")
fit$scores
biplot(fit)
library(psych)
fit1 <- principal(rawData[,unlist(innovation_blocks)], rotate="varimax")
summary(fit)
fit1 <- principal(rawData[,unlist(innovation_blocks)], nfactor = 10,rotate="varimax")
summary(fit)
fit
biplot(fit)
biplot(fit1)
plot(fit1,type="line")
fit3 <- factanal(rawData[,unlist(innovation_blocks)], nfactor = 10,rotate="varimax")
fit3 <- factanal(rawData[,unlist(innovation_blocks)], factors = 10,rotate="varimax")
fit3 <- factanal(rawData[,unlist(innovation_blocks)], factors = 7,rotate="varimax")
fit3 <- factanal(rawData[,unlist(innovation_blocks)], factors = 3,rotate="varimax")
library(nFactors)
library(sem)
library(FactoMineR)
install.packages("nFactors")
install.packages("FactoMineR")
install.packages("sem")
library(nFactors)
fit <- eigen(cor(rawData[,unlist(innovation_blocks)]))
ap <- parallel(subject=nrow(rawData), var=ncol(rawData), rep=100, cent=0.5)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
nS <- nScree(x=fit$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)
ev <- eigen(cor(rawData[,unlist(innovation_blocks)]))
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
temp <- rawData[, unlist(innovation_blocks)]
temp[c(98,137),]
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
?nScree
summary(ap)
summary(ap$eigen)
summary(ev)
summary(ev$values)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
library(FactoMineR)
install.packages("dplyr")
install.packages("dplyr")
install.packages("dplyr")
install.packages("dplyr")
install.packages("dplyr")
install.packages("dplyr")
library(FactoMineR)
library(dplyr)
library(dplyr)
fit <- princomp(temp, cor=TRUE)
fit
biplot(fit)
plot(fit, type="line")
